Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
vt_mask.get_data()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mExpiredDeprecationError[0m                   Traceback (most recent call last)
Cell [0;32mIn[23], line 1[0m
[0;32m----> 1[0m [43mvt_mask[49m[38;5;241;43m.[39;49m[43mget_data[49m[43m([49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nibabel/deprecator.py:224[0m, in [0;36mDeprecator.__call__.<locals>.deprecator.<locals>.deprecated_func[0;34m(*args, **kwargs)[0m
[1;32m    221[0m [38;5;129m@functools[39m[38;5;241m.[39mwraps(func)
[1;32m    222[0m [38;5;28;01mdef[39;00m [38;5;21mdeprecated_func[39m([38;5;241m*[39margs: P[38;5;241m.[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs: P[38;5;241m.[39mkwargs) [38;5;241m-[39m[38;5;241m>[39m T:
[1;32m    223[0m     [38;5;28;01mif[39;00m until [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39mis_bad_version(until):
[0;32m--> 224[0m         [38;5;28;01mraise[39;00m exception(message)
[1;32m    225[0m     warnings[38;5;241m.[39mwarn(message, warning, stacklevel[38;5;241m=[39m[38;5;241m2[39m)
[1;32m    226[0m     [38;5;28;01mreturn[39;00m func([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

[0;31mExpiredDeprecationError[0m: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Raises <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0

